### ISSUE TITLE
more docstrings, type annotations, and numpydoc

### ISSUE THREAD

**Issue by kushalkolar** [project-improv/improv#106]
I can start doing some of this, related #90

**Comment by jmxpearson** [comment]
I assigned you. I’d prioritize the doc strings over type annotations, since I’m not sure how much we want to invest in those until the internal API stabilizes. Users will interact with little API apart from creating their own actors.

**Comment by jmxpearson** [comment]
Closing this for now, since there is similar work ongoing in the docs branch. We can use this for reference.
