### ISSUE TITLE
Formatting error in cli.py

### ISSUE THREAD

**Issue by Tonynanra** [project-improv/improv#125]
The `print` statement on line 241 prints badly formatted messages to `global.log`, which causes pattern matching in`_server_start_logged()` and `_get_ports()` to fail. As of now minimal demo does not work under dev branch.

**Comment by jmxpearson** [comment]
System? Details?There is an automated test for this that currently passes on Mac and Linux. Is there something we’re not catching?On May 30, 2023, at 17:25, Tony ***@***.***> wrote:﻿
The print statement on line 241 prints badly formatted messages to global.log, which causes pattern matching in_server_start_logged() and _get_ports() to fail. As of now minimal demo does not work under dev branch.

**Comment by jmxpearson** [comment]
Closed by #126
