### ISSUE TITLE
Handling errors during actor instantiation

### ISSUE THREAD

**Issue by draelos** [project-improv/improv#141]
Currently it is possible for an actor to fail/crash and everything else in improv to keep running -- this is good, desired behavior. However, if the failure occurs during loading (initialization of all actors, done inside Nexus), then it would be better to immediately notify the user and offer to gracefully shutdown. Likely errors are imports and typos in user code. 
Config should check for these and notify Nexus. Nexus should offer the user a shutdown choice Y/N and the user should use TUI to accept or decline.

**Comment by jmxpearson** [comment]
Are we satisfied that this is handled by #150? There, we don't even get to TUI, but I think that's fine for now.

**Comment by jmxpearson** [comment]
closed by #150
