### ISSUE TITLE
Handle `ModuleImportError` in `config.py` 

### ISSUE THREAD

**Issue by draelos** [project-improv/improv#144]
Agreed to approve this and handle `ModuleImportError` in `config.py` or somewhere similar where we can catch in one place and print out an error message there.

@draelos, I'll let you merge once you've had a look.

_Originally posted by @jmxpearson in https://github.com/project-improv/improv/pull/131#pullrequestreview-1541370084_

**Comment by draelos** [comment]
From earlier comments: https://github.com/project-improv/improv/pull/131#issuecomment-1642808791

**Comment by draelos** [comment]
To do: add requirements.txt file for every demo.

**Comment by jmxpearson** [comment]
Closed by #150
