### ISSUE TITLE
Signal name disambiguation

### ISSUE THREAD

**Issue by draelos** [project-improv/improv#162]
Nexus imports both signal and improv.actor.Signal which itself might be slightly confusing. We then use 'Signal' for Actor-Nexus code (e.g. [Line 377](https://github.com/project-improv/improv/blob/4dd8ff440f10f5be50ecb80db525df6741c92a76/improv/nexus.py#L377)) and for signals in polling like SIGHUP (e.g. [Line 309](https://github.com/project-improv/improv/blob/4dd8ff440f10f5be50ecb80db525df6741c92a76/improv/nexus.py#L309C27-L309C33)).
This might be addressed with sufficient documentation.

However, we also mix up these signals in functions like stop_polling: [here](https://github.com/project-improv/improv/blob/4dd8ff440f10f5be50ecb80db525df6741c92a76/improv/nexus.py#L341) and [here](https://github.com/project-improv/improv/blob/4dd8ff440f10f5be50ecb80db525df6741c92a76/improv/nexus.py#L359), where we pass either a signal like SIGHUP or a Signal like Signal.quit (which is currently "quit" and should also be changed). 
The function stop_polling_and_quit is also relevant here.

**Comment by jmxpearson** [comment]
Thoughts on which we should prefer? Is there functionality in `improv.actor.Signal` that we can’t replace?

**Comment by jmxpearson** [comment]
Oh, I see. We want to treat `run` and `stop` the same way as `kill`. Which argues for using `improv.actor.Signal` everywhere.

**Comment by jmxpearson** [comment]
Closed by #167.
