### ISSUE TITLE
Pyarrow and numpy versions

### ISSUE THREAD

**Issue by draelos** [project-improv/improv#181]
The newer numpy versions (>=2.0.0) are not compatible with the pyarrow version we have fixed (9.0.0). On a limited test on Ubuntu using Python 3.9, downgrading numpy to 1.26 fixed the issue, which was:

`AttributeError: _ARRAY_API not found`

Recommend updating our dependency list.

**Comment by rwschonberg** [comment]
The numpy dependency was pinned to <=1.26 in dev. Can we close this, or should we wait until the merge to main?

**Comment by jmxpearson** [comment]
I updated main because I needed tests to pass with the dependabot PR.
