### ISSUE TITLE
Add list of keys functionality to store

### ISSUE THREAD

**Issue by draelos** [project-improv/improv#187]
Plasma store can take a list of keys or a single key for the .get() function. Redis currently takes single keys only. A wrapper on .get() should be added to account for a list of keys and simply loop over them to return a list of retrieved objects.

**Comment by rwschonberg** [comment]
@draelos following the previous API from the PlasmaStoreInterface, the RedisStoreInterface has the following methods:

- `def get_list(self, ids):`
  - Gets the data for all of the given keys
- `def get_all(self):`
  - Gets all of data from all of the keys currently in the db

Are these sufficient for the use cases you were thinking of?

**Comment by draelos** [comment]
Yep those look perfect. Thanks!
