### ISSUE TITLE
Consolidate installation instructions

### ISSUE THREAD

**Issue by jmxpearson** [project-improv/improv#75]
Need to consolidate installation instructions by adding [this information](https://github.com/project-improv/improv/blob/main/WSLINSTALL.md) to the [Wiki page](https://github.com/project-improv/improv/wiki/Installation), and adding a link to it in [README.md](https://github.com/project-improv/improv/blob/main/README.md).

**Comment by jmxpearson** [comment]
@cyzhou1028 Is this done? Do we have a PR?

**Comment by cyzhou1028** [comment]
Hi Prof,

Yes this is done, just forgot to close the issue
