### ISSUE TITLE
live gridsearch?

### ISSUE THREAD

**Issue by kushalkolar** [project-improv/improv#87]
Just an idea, have you tried doing live narrow gridsearches? I'm guessing this could basically be done by creating multiple instances of the same actor with different parameters. I'll try doing this after getting up my basic stuff up and running.

**Comment by jmxpearson** [comment]
This is an interesting idea. What's the use case?

**Comment by kushalkolar** [comment]
When I'm analysing a new animal I'm never exactly of the params that will be optimal. I'm thinking about the possibility of completelt removing post-acquisition preprocessing!

This should be doable if it's possible to:
1. Specify the same actor class multiple times in the yaml file but with different arguments for the constructor.
2. Link an acquisition actor q_out to these multiple processor q_in

**Comment by jmxpearson** [comment]
I think the second should be no problem. @cyzhou1028 would know if we require no duplicates for the actors, but I doubt that's a restriction. Constructor arguments are given by parameters in the YAML files. I'm pretty sure [`config.py`](https://github.com/project-improv/improv/blob/dev/improv/config.py) forwards all non-appropriated YAML fields to the constructor in a dictionary (cf. [basic demo](https://github.com/project-improv/improv/blob/dev/demos/basic/basic_demo.yaml)).

I think the actors just need to have unique _names_. But the `class` field in the YAML can be reused.
